name: Build, Scan, and Deploy Docker Image to ECR

on:
  push:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # Needed to push manifest changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::334645279807:role/terraform
          aws-region: ap-south-1

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Scan image with Trivy (before push)
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and Push image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in deployment.yaml
        run: |
          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          yq e '.spec.template.spec.containers[0].image = "'${REGISTRY}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}'"' -i k8s/deployment.yaml
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "ci-bot"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${IMAGE_TAG} [ci skip]"
          git pull --rebase origin main
          git push origin main

      - name: Clone the other repo
        run: git clone https://x-access-token:${K8S_REPO_TOKEN}@github.com/shaileshms05/k8.git

      - name: Update deployment.yaml in the other repo
        run: |
          cd <other-repo>
          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          yq e '.spec.template.spec.containers[0].image = "'${REGISTRY}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}'"' -i path/to/deployment.yaml

      - name: Commit and push changes to the other repo
        env:
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_TOKEN }}
        run: |
          cd <other-repo>
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "ci-bot"
          git add path/to/deployment.yaml
          git commit -m "Update image tag to ${IMAGE_TAG} [ci skip]"
          git pull --rebase origin main
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/<username>/<other-repo>.git HEAD:main

      - name: Get K8S repo token from AWS Secrets Manager
        id: get_k8s_token
        run: |
          TOKEN=$(aws secretsmanager get-secret-value --secret-id github/k8s-repo-token --region ap-south-1 --query SecretString --output text | jq -r .K8S_REPO_TOKEN)
          echo "K8S_REPO_TOKEN=$TOKEN" >> $GITHUB_ENV
          echo "K8S_REPO_TOKEN=$TOKEN"
        env:
          AWS_REGION: ap-south-1

      - name: Clone the k8s repo
        run: git clone https://x-access-token:${K8S_REPO_TOKEN}@github.com/shaileshms05/k8.git

      - name: Update deployment.yaml in k8s repo
        run: |
          cd k8/k8s
          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          yq e '.spec.template.spec.containers[0].image = "'${REGISTRY}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}'"' -i deployment.yaml

      - name: Commit and push changes to k8s repo
        run: |
          cd k8
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "ci-bot"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${IMAGE_TAG} [ci skip]"
          git pull --rebase origin main
          git push https://x-access-token:${K8S_REPO_TOKEN}@github.com/shaileshms05/k8.git HEAD:main